#!/bin/bash

while true; 
do 
    cat /mnt/skyrim/Papyrus.0.log | grep "Competent Guards" | tail -10 | \
    awk '/INFO/    {print "\033[32m" $0 "\033[39m"}
         /WARNING/ {print "\033[33m" $0 "\033[39m"}
         /ERROR/   {print "\033[31m" $0 "\033[39m"}'
    sleep 2 && clear; 
done